<?xml version="1.0" encoding="utf-8"?><Database Name="SHRPR" Class="SRPHR_DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SHRPR;Integrated Security=True" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="SHRPRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHDBL" Member="ChiTietHDBLs">
    <Type Name="ChiTietHDBL">
      <Column Name="soHoaDon" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="donGia" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HoaDonBanLe_ChiTietHDBL" Member="HoaDonBanLe" ThisKey="soHoaDon" OtherKey="soHoaDon" Type="HoaDonBanLe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sanpham_ChiTietHDBL" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheThanhVien" Member="TheThanhViens">
    <Type Name="TheThanhVien">
      <Column Name="maKH" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maThe" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="diemTichLuy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayHethan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="KhachHang_TheThanhVien" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Chitietphieuquanlykho" Member="Chitietphieuquanlykhos">
    <Type Name="Chitietphieuquanlykho">
      <Column Name="maPhieuql" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sLuongql" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="donVi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Phieuquanlykho_Chitietphieuquanlykho" Member="Phieuquanlykho" ThisKey="maPhieuql" OtherKey="maPhieuql" Type="Phieuquanlykho" IsForeignKey="true" />
      <Association Name="Sanpham_Chitietphieuquanlykho" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Chucvu" Member="Chucvus">
    <Type Name="Chucvu">
      <Column Name="maChucvu" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="heso" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="tenCV" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Chucvu_LichsuLamviec" Member="LichsuLamviecs" ThisKey="maChucvu" OtherKey="maChucvu" Type="LichsuLamviec" />
    </Type>
  </Table>
  <Table Name="dbo.CongnoKH" Member="CongnoKHs">
    <Type Name="CongnoKH">
      <Column Name="soPhieu" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="maKH" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="CongnoKH_CTCongnoKH" Member="CTCongnoKHs" ThisKey="soPhieu" OtherKey="soPhieu" Type="CTCongnoKH" />
      <Association Name="KhachHang_CongnoKH" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_CongnoKH" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CongNoNCC" Member="CongNoNCCs">
    <Type Name="CongNoNCC">
      <Column Name="soPhieu" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="CongNoNCC_CTCongnoNCC" Member="CTCongnoNCCs" ThisKey="soPhieu" OtherKey="soPhieu" Type="CTCongnoNCC" />
    </Type>
  </Table>
  <Table Name="dbo.CTCongnoKH" Member="CTCongnoKHs">
    <Type Name="CTCongnoKH">
      <Column Name="maKH" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soPhieu" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sotien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="CongnoKH_CTCongnoKH" Member="CongnoKH" ThisKey="soPhieu" OtherKey="soPhieu" Type="CongnoKH" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="KhachHang_CTCongnoKH" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTCongnoNCC" Member="CTCongnoNCCs">
    <Type Name="CTCongnoNCC">
      <Column Name="soPhieu" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maHD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="sotien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="CongNoNCC_CTCongnoNCC" Member="CongNoNCC" ThisKey="soPhieu" OtherKey="soPhieu" Type="CongNoNCC" IsForeignKey="true" />
      <Association Name="HDMuaHangNCC_CTCongnoNCC" Member="HDMuaHangNCC" ThisKey="maHD" OtherKey="maHD" Type="HDMuaHangNCC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTHDBansi" Member="CTHDBansis">
    <Type Name="CTHDBansi">
      <Column Name="maHD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="dongiaBan" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HDBanSi_CTHDBansi" Member="HDBanSi" ThisKey="maHD" OtherKey="maHD" Type="HDBanSi" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sanpham_CTHDBansi" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTKhuyenMai" Member="CTKhuyenMais">
    <Type Name="CTKhuyenMai">
      <Column Name="msDotKM" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="phantramKM" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="KhuyenMai_CTKhuyenMai" Member="KhuyenMai" ThisKey="msDotKM" OtherKey="msDotKM" Type="KhuyenMai" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sanpham_CTKhuyenMai" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTKyluatNV" Member="CTKyluatNVs">
    <Type Name="CTKyluatNV">
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKyluat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hinhthucKL" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayThihanh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKetthuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mucdokl" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lydo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="KyluatNV_CTKyluatNV" Member="KyluatNV" ThisKey="maKyluat" OtherKey="maKyluat" Type="KyluatNV" IsForeignKey="true" />
      <Association Name="NhanVien_CTKyluatNV" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTMuahangNCC" Member="CTMuahangNCCs">
    <Type Name="CTMuahangNCC">
      <Column Name="maSP" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maHD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="dongiaMua" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HDMuaHangNCC_CTMuahangNCC" Member="HDMuaHangNCC" ThisKey="maHD" OtherKey="maHD" Type="HDMuaHangNCC" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuDeNNK" Member="CTPhieuDeNNKs">
    <Type Name="CTPhieuDeNNK">
      <Column Name="soPDNNK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="PhieuDNNK_CTPhieuDeNNK" Member="PhieuDNNK" ThisKey="soPDNNK" OtherKey="soPDNNK" Type="PhieuDNNK" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sanpham_CTPhieuDeNNK" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPhieuDNXK" Member="CTPhieuDNXKs">
    <Type Name="CTPhieuDNXK">
      <Column Name="soPDNXK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Association Name="PhieuDNXK_CTPhieuDNXK" Member="PhieuDNXK" ThisKey="soPDNXK" OtherKey="soPDNNK" Type="PhieuDNXK" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Sanpham_CTPhieuDNXK" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTThamgiaDTNV" Member="CTThamgiaDTNVs">
    <Type Name="CTThamgiaDTNV">
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKhoaDT" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ketQua" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nhanxet" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="DaotaoNV_CTThamgiaDTNV" Member="DaotaoNV" ThisKey="maKhoaDT" OtherKey="maKhoaDT" Type="DaotaoNV" IsForeignKey="true" />
      <Association Name="NhanVien_CTThamgiaDTNV" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DaotaoNV" Member="DaotaoNVs">
    <Type Name="DaotaoNV">
      <Column Name="maKhoaDT" Type="System.String" DbType="NVarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKhoaDT" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="diadiem" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="hinhthucDT" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="chiPhi" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DaotaoNV_CTThamgiaDTNV" Member="CTThamgiaDTNVs" ThisKey="maKhoaDT" OtherKey="maKhoaDT" Type="CTThamgiaDTNV" />
    </Type>
  </Table>
  <Table Name="dbo.HDBanSi" Member="HDBanSis">
    <Type Name="HDBanSi">
      <Column Name="maHD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="maKH" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HDBanSi_CTHDBansi" Member="CTHDBansis" ThisKey="maHD" OtherKey="maHD" Type="CTHDBansi" />
      <Association Name="KhachHang_HDBanSi" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HDBanSi" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HDMuaHangNCC" Member="HDMuaHangNCCs">
    <Type Name="HDMuaHangNCC">
      <Column Name="maHD" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenHD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="maNCC" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="noiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="HDMuaHangNCC_CTCongnoNCC" Member="CTCongnoNCCs" ThisKey="maHD" OtherKey="maHD" Type="CTCongnoNCC" />
      <Association Name="HDMuaHangNCC_CTMuahangNCC" Member="CTMuahangNCCs" ThisKey="maHD" OtherKey="maHD" Type="CTMuahangNCC" />
      <Association Name="NhaCungCap_HDMuaHangNCC" Member="NhaCungCap" ThisKey="maNCC" OtherKey="maNCC" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="NhanVien_HDMuaHangNCC" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HinhanhSP" Member="HinhanhSPs">
    <Type Name="HinhanhSP">
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maHA" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="duongdan" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Sanpham_HinhanhSP" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonBanLe" Member="HoaDonBanLes">
    <Type Name="HoaDonBanLe">
      <Column Name="soHoaDon" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayBan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="maKH" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HoaDonBanLe_ChiTietHDBL" Member="ChiTietHDBLs" ThisKey="soHoaDon" OtherKey="soHoaDon" Type="ChiTietHDBL" />
      <Association Name="HoaDonGTGT_HoaDonBanLe" Member="HoaDonGTGT" ThisKey="soHoaDon" OtherKey="soHoaDon" Type="HoaDonGTGT" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="KhachHang_HoaDonBanLe" Member="KhachHang" ThisKey="maKH" OtherKey="maKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDonBanLe" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonGTGT" Member="HoaDonGTGTs">
    <Type Name="HoaDonGTGT">
      <Column Name="soHoaDon" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dvBanHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dvMuaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="msThue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hinhthucThanhToan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngaylapHoaDon" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="thanhTien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="HoaDonGTGT_HoaDonBanLe" Member="HoaDonBanLe" ThisKey="soHoaDon" OtherKey="soHoaDon" Type="HoaDonBanLe" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="maKH" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="soCMND" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ngaycapCMND" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="sodienthoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="nghenghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_TheThanhVien" Member="TheThanhVien" ThisKey="maKH" OtherKey="maKH" Type="TheThanhVien" Cardinality="One" />
      <Association Name="KhachHang_CongnoKH" Member="CongnoKHs" ThisKey="maKH" OtherKey="maKH" Type="CongnoKH" />
      <Association Name="KhachHang_CTCongnoKH" Member="CTCongnoKHs" ThisKey="maKH" OtherKey="maKH" Type="CTCongnoKH" />
      <Association Name="KhachHang_HDBanSi" Member="HDBanSis" ThisKey="maKH" OtherKey="maKH" Type="HDBanSi" />
      <Association Name="KhachHang_HoaDonBanLe" Member="HoaDonBanLes" ThisKey="maKH" OtherKey="maKH" Type="HoaDonBanLe" />
    </Type>
  </Table>
  <Table Name="dbo.Kho" Member="Khos">
    <Type Name="Kho">
      <Column Name="msKho" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKho" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="diachiKho" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Kho_Phieunhapkho" Member="Phieunhapkhos" ThisKey="msKho" OtherKey="msKho" Type="Phieunhapkho" />
      <Association Name="Kho_Phieuquanlykho" Member="Phieuquanlykhos" ThisKey="msKho" OtherKey="msKho" Type="Phieuquanlykho" />
      <Association Name="PhongBan_Kho" Member="PhongBan" ThisKey="msKho" OtherKey="maPB" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMai" Member="KhuyenMais">
    <Type Name="KhuyenMai">
      <Column Name="msDotKM" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenDotKM" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="KhuyenMai_CTKhuyenMai" Member="CTKhuyenMais" ThisKey="msDotKM" OtherKey="msDotKM" Type="CTKhuyenMai" />
    </Type>
  </Table>
  <Table Name="dbo.KyluatNV" Member="KyluatNVs">
    <Type Name="KyluatNV">
      <Column Name="maKyluat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hinhthucKL" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="KyluatNV_CTKyluatNV" Member="CTKyluatNVs" ThisKey="maKyluat" OtherKey="maKyluat" Type="CTKyluatNV" />
    </Type>
  </Table>
  <Table Name="dbo.LichsuLamviec" Member="LichsuLamviecs">
    <Type Name="LichsuLamviec">
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maPB" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maChucvu" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ngayBD" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Chucvu_LichsuLamviec" Member="Chucvu" ThisKey="maChucvu" OtherKey="maChucvu" Type="Chucvu" IsForeignKey="true" />
      <Association Name="NhanVien_LichsuLamviec" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="PhongBan_LichsuLamviec" Member="PhongBan" ThisKey="maPB" OtherKey="maPB" Type="PhongBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ModuleTinhGia" Member="ModuleTinhGias">
    <Type Name="ModuleTinhGia">
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="giaBan" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ngayLapGia" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayHetHieuLuc" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Sanpham_ModuleTinhGia" Member="Sanpham" ThisKey="maSP" OtherKey="maSP" Type="Sanpham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="maNCC" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="diaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sDT" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="NhaCungCap_HDMuaHangNCC" Member="HDMuaHangNCCs" ThisKey="maNCC" OtherKey="maNCC" Type="HDMuaHangNCC" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ngaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayVaoLam" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="soCMND" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ngayCapCMND" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gioitinh" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NhanVien_CongnoKH" Member="CongnoKHs" ThisKey="maNV" OtherKey="maNV" Type="CongnoKH" />
      <Association Name="NhanVien_CTKyluatNV" Member="CTKyluatNVs" ThisKey="maNV" OtherKey="maNV" Type="CTKyluatNV" />
      <Association Name="NhanVien_CTThamgiaDTNV" Member="CTThamgiaDTNVs" ThisKey="maNV" OtherKey="maNV" Type="CTThamgiaDTNV" />
      <Association Name="NhanVien_HDBanSi" Member="HDBanSis" ThisKey="maNV" OtherKey="maNV" Type="HDBanSi" />
      <Association Name="NhanVien_HDMuaHangNCC" Member="HDMuaHangNCCs" ThisKey="maNV" OtherKey="maNV" Type="HDMuaHangNCC" />
      <Association Name="NhanVien_HoaDonBanLe" Member="HoaDonBanLes" ThisKey="maNV" OtherKey="maNV" Type="HoaDonBanLe" />
      <Association Name="NhanVien_LichsuLamviec" Member="LichsuLamviecs" ThisKey="maNV" OtherKey="maNV" Type="LichsuLamviec" />
      <Association Name="NhanVien_PhieuDNNK" Member="PhieuDNNKs" ThisKey="maNV" OtherKey="maNV" Type="PhieuDNNK" />
      <Association Name="NhanVien_PhieuDNXK" Member="PhieuDNXKs" ThisKey="maNV" OtherKey="maNV" Type="PhieuDNXK" />
      <Association Name="NhanVien_PhieuDNXK1" Member="PhieuDNXKs1" ThisKey="maNV" OtherKey="maNV" Type="PhieuDNXK" />
      <Association Name="NhanVien_Phieunhapkho" Member="Phieunhapkhos" ThisKey="maNV" OtherKey="maNv" Type="Phieunhapkho" />
      <Association Name="NhanVien_Phieuquanlykho" Member="Phieuquanlykhos" ThisKey="maNV" OtherKey="maNv" Type="Phieuquanlykho" />
      <Association Name="NhanVien_Phieuxuatkho" Member="Phieuxuatkhos" ThisKey="maNV" OtherKey="maNV" Type="Phieuxuatkho" />
      <Association Name="NhanVien_Phieuxuatkho1" Member="Phieuxuatkhos1" ThisKey="maNV" OtherKey="maNV" Type="Phieuxuatkho" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDNNK" Member="PhieuDNNKs">
    <Type Name="PhieuDNNK">
      <Column Name="soPDNNK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLapphieu" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="maKho" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDNNK_CTPhieuDeNNK" Member="CTPhieuDeNNKs" ThisKey="soPDNNK" OtherKey="soPDNNK" Type="CTPhieuDeNNK" />
      <Association Name="PhieuDNNK_Phieunhapkho" Member="Phieunhapkho" ThisKey="soPDNNK" OtherKey="maPhieunhap" Type="Phieunhapkho" Cardinality="One" />
      <Association Name="NhanVien_PhieuDNNK" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDNXK" Member="PhieuDNXKs">
    <Type Name="PhieuDNXK">
      <Column Name="soPDNNK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="maKho" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDNXK_CTPhieuDNXK" Member="CTPhieuDNXKs" ThisKey="soPDNNK" OtherKey="soPDNXK" Type="CTPhieuDNXK" />
      <Association Name="PhieuDNXK_Phieuxuatkho" Member="Phieuxuatkho" ThisKey="soPDNNK" OtherKey="maPhieuxuat" Type="Phieuxuatkho" Cardinality="One" />
      <Association Name="NhanVien_PhieuDNXK" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="NhanVien_PhieuDNXK1" Member="NhanVien1" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phieunhapkho" Member="Phieunhapkhos">
    <Type Name="Phieunhapkho">
      <Column Name="maPhieunhap" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLapnhap" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="maNv" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="msKho" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Kho_Phieunhapkho" Member="Kho" ThisKey="msKho" OtherKey="msKho" Type="Kho" IsForeignKey="true" />
      <Association Name="NhanVien_Phieunhapkho" Member="NhanVien" ThisKey="maNv" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="PhieuDNNK_Phieunhapkho" Member="PhieuDNNK" ThisKey="maPhieunhap" OtherKey="soPDNNK" Type="PhieuDNNK" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phieuquanlykho" Member="Phieuquanlykhos">
    <Type Name="Phieuquanlykho">
      <Column Name="maPhieuql" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLapql" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maNv" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="msKho" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Phieuquanlykho_Chitietphieuquanlykho" Member="Chitietphieuquanlykhos" ThisKey="maPhieuql" OtherKey="maPhieuql" Type="Chitietphieuquanlykho" />
      <Association Name="Kho_Phieuquanlykho" Member="Kho" ThisKey="msKho" OtherKey="msKho" Type="Kho" IsForeignKey="true" />
      <Association Name="NhanVien_Phieuquanlykho" Member="NhanVien" ThisKey="maNv" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phieuxuatkho" Member="Phieuxuatkhos">
    <Type Name="Phieuxuatkho">
      <Column Name="maPhieuxuat" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayLapxuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maNV" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tinhTrang" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="NhanVien_Phieuxuatkho" Member="NhanVien" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="NhanVien_Phieuxuatkho1" Member="NhanVien1" ThisKey="maNV" OtherKey="maNV" Type="NhanVien" IsForeignKey="true" />
      <Association Name="PhieuDNXK_Phieuxuatkho" Member="PhieuDNXK" ThisKey="maPhieuxuat" OtherKey="soPDNNK" Type="PhieuDNXK" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="maPB" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenPB" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="diaDiem" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="soDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="PhongBan_Kho" Member="Kho" ThisKey="maPB" OtherKey="msKho" Type="Kho" Cardinality="One" />
      <Association Name="PhongBan_LichsuLamviec" Member="LichsuLamviecs" ThisKey="maPB" OtherKey="maPB" Type="LichsuLamviec" />
    </Type>
  </Table>
  <Table Name="dbo.Sanpham" Member="Sanphams">
    <Type Name="Sanpham">
      <Column Name="maSP" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenSP" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="mota" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ngaySX" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="hanSD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tenNhaPP" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="tenNhaSX" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="trangThai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sanpham_ChiTietHDBL" Member="ChiTietHDBLs" ThisKey="maSP" OtherKey="maSP" Type="ChiTietHDBL" />
      <Association Name="Sanpham_Chitietphieuquanlykho" Member="Chitietphieuquanlykhos" ThisKey="maSP" OtherKey="maSP" Type="Chitietphieuquanlykho" />
      <Association Name="Sanpham_CTHDBansi" Member="CTHDBansis" ThisKey="maSP" OtherKey="maSP" Type="CTHDBansi" />
      <Association Name="Sanpham_CTKhuyenMai" Member="CTKhuyenMais" ThisKey="maSP" OtherKey="maSP" Type="CTKhuyenMai" />
      <Association Name="Sanpham_CTPhieuDeNNK" Member="CTPhieuDeNNKs" ThisKey="maSP" OtherKey="maSP" Type="CTPhieuDeNNK" />
      <Association Name="Sanpham_CTPhieuDNXK" Member="CTPhieuDNXKs" ThisKey="maSP" OtherKey="maSP" Type="CTPhieuDNXK" />
      <Association Name="Sanpham_HinhanhSP" Member="HinhanhSPs" ThisKey="maSP" OtherKey="maSP" Type="HinhanhSP" />
      <Association Name="Sanpham_ModuleTinhGia" Member="ModuleTinhGias" ThisKey="maSP" OtherKey="maSP" Type="ModuleTinhGia" />
    </Type>
  </Table>
</Database>