#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.NhanSu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHRPR1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_CTKyLuatNV(Tbl_CTKyLuatNV instance);
    partial void UpdateTbl_CTKyLuatNV(Tbl_CTKyLuatNV instance);
    partial void DeleteTbl_CTKyLuatNV(Tbl_CTKyLuatNV instance);
    partial void InsertTbl_CTThamGiaDTNV(Tbl_CTThamGiaDTNV instance);
    partial void UpdateTbl_CTThamGiaDTNV(Tbl_CTThamGiaDTNV instance);
    partial void DeleteTbl_CTThamGiaDTNV(Tbl_CTThamGiaDTNV instance);
    partial void InsertTbl_ChucVu(Tbl_ChucVu instance);
    partial void UpdateTbl_ChucVu(Tbl_ChucVu instance);
    partial void DeleteTbl_ChucVu(Tbl_ChucVu instance);
    partial void InsertTbl_DaoTaoNV(Tbl_DaoTaoNV instance);
    partial void UpdateTbl_DaoTaoNV(Tbl_DaoTaoNV instance);
    partial void DeleteTbl_DaoTaoNV(Tbl_DaoTaoNV instance);
    partial void InsertTbl_KyLuatNV(Tbl_KyLuatNV instance);
    partial void UpdateTbl_KyLuatNV(Tbl_KyLuatNV instance);
    partial void DeleteTbl_KyLuatNV(Tbl_KyLuatNV instance);
    partial void InsertTbl_NhanVien(Tbl_NhanVien instance);
    partial void UpdateTbl_NhanVien(Tbl_NhanVien instance);
    partial void DeleteTbl_NhanVien(Tbl_NhanVien instance);
    partial void InsertTbl_PhongBan(Tbl_PhongBan instance);
    partial void UpdateTbl_PhongBan(Tbl_PhongBan instance);
    partial void DeleteTbl_PhongBan(Tbl_PhongBan instance);
    partial void InsertTbl_LichSuLamViec(Tbl_LichSuLamViec instance);
    partial void UpdateTbl_LichSuLamViec(Tbl_LichSuLamViec instance);
    partial void DeleteTbl_LichSuLamViec(Tbl_LichSuLamViec instance);
    partial void InsertTbl_User(Tbl_User instance);
    partial void UpdateTbl_User(Tbl_User instance);
    partial void DeleteTbl_User(Tbl_User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DataAccess.Properties.Settings.Default.SHRPRConnectionString6, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_CTKyLuatNV> Tbl_CTKyLuatNVs
		{
			get
			{
				return this.GetTable<Tbl_CTKyLuatNV>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_CTThamGiaDTNV> Tbl_CTThamGiaDTNVs
		{
			get
			{
				return this.GetTable<Tbl_CTThamGiaDTNV>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_ChucVu> Tbl_ChucVus
		{
			get
			{
				return this.GetTable<Tbl_ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_DaoTaoNV> Tbl_DaoTaoNVs
		{
			get
			{
				return this.GetTable<Tbl_DaoTaoNV>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_KyLuatNV> Tbl_KyLuatNVs
		{
			get
			{
				return this.GetTable<Tbl_KyLuatNV>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_NhanVien> Tbl_NhanViens
		{
			get
			{
				return this.GetTable<Tbl_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_PhongBan> Tbl_PhongBans
		{
			get
			{
				return this.GetTable<Tbl_PhongBan>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_LichSuLamViec> Tbl_LichSuLamViecs
		{
			get
			{
				return this.GetTable<Tbl_LichSuLamViec>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_User> Tbl_Users
		{
			get
			{
				return this.GetTable<Tbl_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CTKyLuatNV")]
	public partial class Tbl_CTKyLuatNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _maKyLuat;
		
		private string _hinhThucKL;
		
		private System.DateTime _ngayLap;
		
		private System.DateTime _ngayThiHanh;
		
		private System.DateTime _ngayKetThuc;
		
		private string _mucDoKL;
		
		private string _lyDo;
		
		private string _ghiChu;
		
		private EntityRef<Tbl_KyLuatNV> _Tbl_KyLuatNV;
		
		private EntityRef<Tbl_NhanVien> _Tbl_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKyLuatChanging(string value);
    partial void OnmaKyLuatChanged();
    partial void OnhinhThucKLChanging(string value);
    partial void OnhinhThucKLChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    partial void OnngayThiHanhChanging(System.DateTime value);
    partial void OnngayThiHanhChanged();
    partial void OnngayKetThucChanging(System.DateTime value);
    partial void OnngayKetThucChanged();
    partial void OnmucDoKLChanging(string value);
    partial void OnmucDoKLChanged();
    partial void OnlyDoChanging(string value);
    partial void OnlyDoChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public Tbl_CTKyLuatNV()
		{
			this._Tbl_KyLuatNV = default(EntityRef<Tbl_KyLuatNV>);
			this._Tbl_NhanVien = default(EntityRef<Tbl_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._Tbl_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKyLuat", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKyLuat
		{
			get
			{
				return this._maKyLuat;
			}
			set
			{
				if ((this._maKyLuat != value))
				{
					if (this._Tbl_KyLuatNV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKyLuatChanging(value);
					this.SendPropertyChanging();
					this._maKyLuat = value;
					this.SendPropertyChanged("maKyLuat");
					this.OnmaKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhThucKL", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string hinhThucKL
		{
			get
			{
				return this._hinhThucKL;
			}
			set
			{
				if ((this._hinhThucKL != value))
				{
					this.OnhinhThucKLChanging(value);
					this.SendPropertyChanging();
					this._hinhThucKL = value;
					this.SendPropertyChanged("hinhThucKL");
					this.OnhinhThucKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="Date NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayThiHanh", DbType="Date NOT NULL")]
		public System.DateTime ngayThiHanh
		{
			get
			{
				return this._ngayThiHanh;
			}
			set
			{
				if ((this._ngayThiHanh != value))
				{
					this.OnngayThiHanhChanging(value);
					this.SendPropertyChanging();
					this._ngayThiHanh = value;
					this.SendPropertyChanged("ngayThiHanh");
					this.OnngayThiHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKetThuc", DbType="Date NOT NULL")]
		public System.DateTime ngayKetThuc
		{
			get
			{
				return this._ngayKetThuc;
			}
			set
			{
				if ((this._ngayKetThuc != value))
				{
					this.OnngayKetThucChanging(value);
					this.SendPropertyChanging();
					this._ngayKetThuc = value;
					this.SendPropertyChanged("ngayKetThuc");
					this.OnngayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucDoKL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string mucDoKL
		{
			get
			{
				return this._mucDoKL;
			}
			set
			{
				if ((this._mucDoKL != value))
				{
					this.OnmucDoKLChanging(value);
					this.SendPropertyChanging();
					this._mucDoKL = value;
					this.SendPropertyChanged("mucDoKL");
					this.OnmucDoKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lyDo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lyDo
		{
			get
			{
				return this._lyDo;
			}
			set
			{
				if ((this._lyDo != value))
				{
					this.OnlyDoChanging(value);
					this.SendPropertyChanging();
					this._lyDo = value;
					this.SendPropertyChanged("lyDo");
					this.OnlyDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(150)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_KyLuatNV_Tbl_CTKyLuatNV", Storage="_Tbl_KyLuatNV", ThisKey="maKyLuat", OtherKey="maKyLuat", IsForeignKey=true)]
		public Tbl_KyLuatNV Tbl_KyLuatNV
		{
			get
			{
				return this._Tbl_KyLuatNV.Entity;
			}
			set
			{
				Tbl_KyLuatNV previousValue = this._Tbl_KyLuatNV.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_KyLuatNV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_KyLuatNV.Entity = null;
						previousValue.Tbl_CTKyLuatNVs.Remove(this);
					}
					this._Tbl_KyLuatNV.Entity = value;
					if ((value != null))
					{
						value.Tbl_CTKyLuatNVs.Add(this);
						this._maKyLuat = value.maKyLuat;
					}
					else
					{
						this._maKyLuat = default(string);
					}
					this.SendPropertyChanged("Tbl_KyLuatNV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NhanVien_Tbl_CTKyLuatNV", Storage="_Tbl_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public Tbl_NhanVien Tbl_NhanVien
		{
			get
			{
				return this._Tbl_NhanVien.Entity;
			}
			set
			{
				Tbl_NhanVien previousValue = this._Tbl_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_NhanVien.Entity = null;
						previousValue.Tbl_CTKyLuatNVs.Remove(this);
					}
					this._Tbl_NhanVien.Entity = value;
					if ((value != null))
					{
						value.Tbl_CTKyLuatNVs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("Tbl_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_CTThamGiaDTNV")]
	public partial class Tbl_CTThamGiaDTNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _maKhoaDT;
		
		private string _ketQua;
		
		private string _nhanXet;
		
		private EntityRef<Tbl_DaoTaoNV> _Tbl_DaoTaoNV;
		
		private EntityRef<Tbl_NhanVien> _Tbl_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaKhoaDTChanging(string value);
    partial void OnmaKhoaDTChanged();
    partial void OnketQuaChanging(string value);
    partial void OnketQuaChanged();
    partial void OnnhanXetChanging(string value);
    partial void OnnhanXetChanged();
    #endregion
		
		public Tbl_CTThamGiaDTNV()
		{
			this._Tbl_DaoTaoNV = default(EntityRef<Tbl_DaoTaoNV>);
			this._Tbl_NhanVien = default(EntityRef<Tbl_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._Tbl_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoaDT", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhoaDT
		{
			get
			{
				return this._maKhoaDT;
			}
			set
			{
				if ((this._maKhoaDT != value))
				{
					if (this._Tbl_DaoTaoNV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhoaDTChanging(value);
					this.SendPropertyChanging();
					this._maKhoaDT = value;
					this.SendPropertyChanged("maKhoaDT");
					this.OnmaKhoaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ketQua", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ketQua
		{
			get
			{
				return this._ketQua;
			}
			set
			{
				if ((this._ketQua != value))
				{
					this.OnketQuaChanging(value);
					this.SendPropertyChanging();
					this._ketQua = value;
					this.SendPropertyChanged("ketQua");
					this.OnketQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhanXet", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string nhanXet
		{
			get
			{
				return this._nhanXet;
			}
			set
			{
				if ((this._nhanXet != value))
				{
					this.OnnhanXetChanging(value);
					this.SendPropertyChanging();
					this._nhanXet = value;
					this.SendPropertyChanged("nhanXet");
					this.OnnhanXetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DaoTaoNV_Tbl_CTThamGiaDTNV", Storage="_Tbl_DaoTaoNV", ThisKey="maKhoaDT", OtherKey="maKhoaDT", IsForeignKey=true)]
		public Tbl_DaoTaoNV Tbl_DaoTaoNV
		{
			get
			{
				return this._Tbl_DaoTaoNV.Entity;
			}
			set
			{
				Tbl_DaoTaoNV previousValue = this._Tbl_DaoTaoNV.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_DaoTaoNV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_DaoTaoNV.Entity = null;
						previousValue.Tbl_CTThamGiaDTNVs.Remove(this);
					}
					this._Tbl_DaoTaoNV.Entity = value;
					if ((value != null))
					{
						value.Tbl_CTThamGiaDTNVs.Add(this);
						this._maKhoaDT = value.maKhoaDT;
					}
					else
					{
						this._maKhoaDT = default(string);
					}
					this.SendPropertyChanged("Tbl_DaoTaoNV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NhanVien_Tbl_CTThamGiaDTNV", Storage="_Tbl_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true)]
		public Tbl_NhanVien Tbl_NhanVien
		{
			get
			{
				return this._Tbl_NhanVien.Entity;
			}
			set
			{
				Tbl_NhanVien previousValue = this._Tbl_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_NhanVien.Entity = null;
						previousValue.Tbl_CTThamGiaDTNVs.Remove(this);
					}
					this._Tbl_NhanVien.Entity = value;
					if ((value != null))
					{
						value.Tbl_CTThamGiaDTNVs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("Tbl_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_ChucVu")]
	public partial class Tbl_ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maChucVu;
		
		private decimal _heSo;
		
		private string _tenCV;
		
		private string _ghiChu;
		
		private EntitySet<Tbl_LichSuLamViec> _Tbl_LichSuLamViecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChucVuChanging(string value);
    partial void OnmaChucVuChanged();
    partial void OnheSoChanging(decimal value);
    partial void OnheSoChanged();
    partial void OntenCVChanging(string value);
    partial void OntenCVChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public Tbl_ChucVu()
		{
			this._Tbl_LichSuLamViecs = new EntitySet<Tbl_LichSuLamViec>(new Action<Tbl_LichSuLamViec>(this.attach_Tbl_LichSuLamViecs), new Action<Tbl_LichSuLamViec>(this.detach_Tbl_LichSuLamViecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heSo", DbType="Money NOT NULL")]
		public decimal heSo
		{
			get
			{
				return this._heSo;
			}
			set
			{
				if ((this._heSo != value))
				{
					this.OnheSoChanging(value);
					this.SendPropertyChanging();
					this._heSo = value;
					this.SendPropertyChanged("heSo");
					this.OnheSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCV", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string tenCV
		{
			get
			{
				return this._tenCV;
			}
			set
			{
				if ((this._tenCV != value))
				{
					this.OntenCVChanging(value);
					this.SendPropertyChanging();
					this._tenCV = value;
					this.SendPropertyChanged("tenCV");
					this.OntenCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(15)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_ChucVu_Tbl_LichSuLamViec", Storage="_Tbl_LichSuLamViecs", ThisKey="maChucVu", OtherKey="maChucVu")]
		public EntitySet<Tbl_LichSuLamViec> Tbl_LichSuLamViecs
		{
			get
			{
				return this._Tbl_LichSuLamViecs;
			}
			set
			{
				this._Tbl_LichSuLamViecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_LichSuLamViecs(Tbl_LichSuLamViec entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_ChucVu = this;
		}
		
		private void detach_Tbl_LichSuLamViecs(Tbl_LichSuLamViec entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_DaoTaoNV")]
	public partial class Tbl_DaoTaoNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhoaDT;
		
		private string _tenKhoaDT;
		
		private System.DateTime _ngayBD;
		
		private System.DateTime _ngayKT;
		
		private string _diaDiem;
		
		private string _hinhthucDT;
		
		private System.Nullable<decimal> _chiPhi;
		
		private EntitySet<Tbl_CTThamGiaDTNV> _Tbl_CTThamGiaDTNVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhoaDTChanging(string value);
    partial void OnmaKhoaDTChanged();
    partial void OntenKhoaDTChanging(string value);
    partial void OntenKhoaDTChanged();
    partial void OnngayBDChanging(System.DateTime value);
    partial void OnngayBDChanged();
    partial void OnngayKTChanging(System.DateTime value);
    partial void OnngayKTChanged();
    partial void OndiaDiemChanging(string value);
    partial void OndiaDiemChanged();
    partial void OnhinhthucDTChanging(string value);
    partial void OnhinhthucDTChanged();
    partial void OnchiPhiChanging(System.Nullable<decimal> value);
    partial void OnchiPhiChanged();
    #endregion
		
		public Tbl_DaoTaoNV()
		{
			this._Tbl_CTThamGiaDTNVs = new EntitySet<Tbl_CTThamGiaDTNV>(new Action<Tbl_CTThamGiaDTNV>(this.attach_Tbl_CTThamGiaDTNVs), new Action<Tbl_CTThamGiaDTNV>(this.detach_Tbl_CTThamGiaDTNVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhoaDT", DbType="NVarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhoaDT
		{
			get
			{
				return this._maKhoaDT;
			}
			set
			{
				if ((this._maKhoaDT != value))
				{
					this.OnmaKhoaDTChanging(value);
					this.SendPropertyChanging();
					this._maKhoaDT = value;
					this.SendPropertyChanged("maKhoaDT");
					this.OnmaKhoaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhoaDT", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string tenKhoaDT
		{
			get
			{
				return this._tenKhoaDT;
			}
			set
			{
				if ((this._tenKhoaDT != value))
				{
					this.OntenKhoaDTChanging(value);
					this.SendPropertyChanging();
					this._tenKhoaDT = value;
					this.SendPropertyChanged("tenKhoaDT");
					this.OntenKhoaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBD", DbType="Date NOT NULL")]
		public System.DateTime ngayBD
		{
			get
			{
				return this._ngayBD;
			}
			set
			{
				if ((this._ngayBD != value))
				{
					this.OnngayBDChanging(value);
					this.SendPropertyChanging();
					this._ngayBD = value;
					this.SendPropertyChanged("ngayBD");
					this.OnngayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKT", DbType="Date NOT NULL")]
		public System.DateTime ngayKT
		{
			get
			{
				return this._ngayKT;
			}
			set
			{
				if ((this._ngayKT != value))
				{
					this.OnngayKTChanging(value);
					this.SendPropertyChanging();
					this._ngayKT = value;
					this.SendPropertyChanged("ngayKT");
					this.OnngayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaDiem", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string diaDiem
		{
			get
			{
				return this._diaDiem;
			}
			set
			{
				if ((this._diaDiem != value))
				{
					this.OndiaDiemChanging(value);
					this.SendPropertyChanging();
					this._diaDiem = value;
					this.SendPropertyChanged("diaDiem");
					this.OndiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhthucDT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string hinhthucDT
		{
			get
			{
				return this._hinhthucDT;
			}
			set
			{
				if ((this._hinhthucDT != value))
				{
					this.OnhinhthucDTChanging(value);
					this.SendPropertyChanging();
					this._hinhthucDT = value;
					this.SendPropertyChanged("hinhthucDT");
					this.OnhinhthucDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiPhi", DbType="Money")]
		public System.Nullable<decimal> chiPhi
		{
			get
			{
				return this._chiPhi;
			}
			set
			{
				if ((this._chiPhi != value))
				{
					this.OnchiPhiChanging(value);
					this.SendPropertyChanging();
					this._chiPhi = value;
					this.SendPropertyChanged("chiPhi");
					this.OnchiPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_DaoTaoNV_Tbl_CTThamGiaDTNV", Storage="_Tbl_CTThamGiaDTNVs", ThisKey="maKhoaDT", OtherKey="maKhoaDT")]
		public EntitySet<Tbl_CTThamGiaDTNV> Tbl_CTThamGiaDTNVs
		{
			get
			{
				return this._Tbl_CTThamGiaDTNVs;
			}
			set
			{
				this._Tbl_CTThamGiaDTNVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_CTThamGiaDTNVs(Tbl_CTThamGiaDTNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DaoTaoNV = this;
		}
		
		private void detach_Tbl_CTThamGiaDTNVs(Tbl_CTThamGiaDTNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_DaoTaoNV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_KyLuatNV")]
	public partial class Tbl_KyLuatNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKyLuat;
		
		private string _hinhThucKL;
		
		private string _ghiChu;
		
		private EntitySet<Tbl_CTKyLuatNV> _Tbl_CTKyLuatNVs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKyLuatChanging(string value);
    partial void OnmaKyLuatChanged();
    partial void OnhinhThucKLChanging(string value);
    partial void OnhinhThucKLChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public Tbl_KyLuatNV()
		{
			this._Tbl_CTKyLuatNVs = new EntitySet<Tbl_CTKyLuatNV>(new Action<Tbl_CTKyLuatNV>(this.attach_Tbl_CTKyLuatNVs), new Action<Tbl_CTKyLuatNV>(this.detach_Tbl_CTKyLuatNVs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKyLuat", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKyLuat
		{
			get
			{
				return this._maKyLuat;
			}
			set
			{
				if ((this._maKyLuat != value))
				{
					this.OnmaKyLuatChanging(value);
					this.SendPropertyChanging();
					this._maKyLuat = value;
					this.SendPropertyChanged("maKyLuat");
					this.OnmaKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhThucKL", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string hinhThucKL
		{
			get
			{
				return this._hinhThucKL;
			}
			set
			{
				if ((this._hinhThucKL != value))
				{
					this.OnhinhThucKLChanging(value);
					this.SendPropertyChanging();
					this._hinhThucKL = value;
					this.SendPropertyChanged("hinhThucKL");
					this.OnhinhThucKLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(250)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_KyLuatNV_Tbl_CTKyLuatNV", Storage="_Tbl_CTKyLuatNVs", ThisKey="maKyLuat", OtherKey="maKyLuat")]
		public EntitySet<Tbl_CTKyLuatNV> Tbl_CTKyLuatNVs
		{
			get
			{
				return this._Tbl_CTKyLuatNVs;
			}
			set
			{
				this._Tbl_CTKyLuatNVs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_CTKyLuatNVs(Tbl_CTKyLuatNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_KyLuatNV = this;
		}
		
		private void detach_Tbl_CTKyLuatNVs(Tbl_CTKyLuatNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_KyLuatNV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_NhanVien")]
	public partial class Tbl_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _hoTen;
		
		private System.DateTime _ngaySinh;
		
		private System.DateTime _ngayVaoLam;
		
		private string _soCMND;
		
		private System.DateTime _ngayCapCMND;
		
		private string _gioiTinh;
		
		private string _email;
		
		private string _soDT;
		
		private string _diaChi;
		
		private System.Nullable<int> _trangThai;
		
		private EntitySet<Tbl_CTKyLuatNV> _Tbl_CTKyLuatNVs;
		
		private EntitySet<Tbl_CTThamGiaDTNV> _Tbl_CTThamGiaDTNVs;
		
		private EntitySet<Tbl_LichSuLamViec> _Tbl_LichSuLamViecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnngaySinhChanging(System.DateTime value);
    partial void OnngaySinhChanged();
    partial void OnngayVaoLamChanging(System.DateTime value);
    partial void OnngayVaoLamChanged();
    partial void OnsoCMNDChanging(string value);
    partial void OnsoCMNDChanged();
    partial void OnngayCapCMNDChanging(System.DateTime value);
    partial void OnngayCapCMNDChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OntrangThaiChanging(System.Nullable<int> value);
    partial void OntrangThaiChanged();
    #endregion
		
		public Tbl_NhanVien()
		{
			this._Tbl_CTKyLuatNVs = new EntitySet<Tbl_CTKyLuatNV>(new Action<Tbl_CTKyLuatNV>(this.attach_Tbl_CTKyLuatNVs), new Action<Tbl_CTKyLuatNV>(this.detach_Tbl_CTKyLuatNVs));
			this._Tbl_CTThamGiaDTNVs = new EntitySet<Tbl_CTThamGiaDTNV>(new Action<Tbl_CTThamGiaDTNV>(this.attach_Tbl_CTThamGiaDTNVs), new Action<Tbl_CTThamGiaDTNV>(this.detach_Tbl_CTThamGiaDTNVs));
			this._Tbl_LichSuLamViecs = new EntitySet<Tbl_LichSuLamViec>(new Action<Tbl_LichSuLamViec>(this.attach_Tbl_LichSuLamViecs), new Action<Tbl_LichSuLamViec>(this.detach_Tbl_LichSuLamViecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaySinh", DbType="Date NOT NULL")]
		public System.DateTime ngaySinh
		{
			get
			{
				return this._ngaySinh;
			}
			set
			{
				if ((this._ngaySinh != value))
				{
					this.OnngaySinhChanging(value);
					this.SendPropertyChanging();
					this._ngaySinh = value;
					this.SendPropertyChanged("ngaySinh");
					this.OnngaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayVaoLam", DbType="Date NOT NULL")]
		public System.DateTime ngayVaoLam
		{
			get
			{
				return this._ngayVaoLam;
			}
			set
			{
				if ((this._ngayVaoLam != value))
				{
					this.OnngayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._ngayVaoLam = value;
					this.SendPropertyChanged("ngayVaoLam");
					this.OnngayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soCMND", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string soCMND
		{
			get
			{
				return this._soCMND;
			}
			set
			{
				if ((this._soCMND != value))
				{
					this.OnsoCMNDChanging(value);
					this.SendPropertyChanging();
					this._soCMND = value;
					this.SendPropertyChanged("soCMND");
					this.OnsoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCapCMND", DbType="Date NOT NULL")]
		public System.DateTime ngayCapCMND
		{
			get
			{
				return this._ngayCapCMND;
			}
			set
			{
				if ((this._ngayCapCMND != value))
				{
					this.OnngayCapCMNDChanging(value);
					this.SendPropertyChanging();
					this._ngayCapCMND = value;
					this.SendPropertyChanged("ngayCapCMND");
					this.OnngayCapCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="Int")]
		public System.Nullable<int> trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NhanVien_Tbl_CTKyLuatNV", Storage="_Tbl_CTKyLuatNVs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<Tbl_CTKyLuatNV> Tbl_CTKyLuatNVs
		{
			get
			{
				return this._Tbl_CTKyLuatNVs;
			}
			set
			{
				this._Tbl_CTKyLuatNVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NhanVien_Tbl_CTThamGiaDTNV", Storage="_Tbl_CTThamGiaDTNVs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<Tbl_CTThamGiaDTNV> Tbl_CTThamGiaDTNVs
		{
			get
			{
				return this._Tbl_CTThamGiaDTNVs;
			}
			set
			{
				this._Tbl_CTThamGiaDTNVs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NhanVien_Tbl_LichSuLamViec", Storage="_Tbl_LichSuLamViecs", ThisKey="maNV", OtherKey="maNV")]
		public EntitySet<Tbl_LichSuLamViec> Tbl_LichSuLamViecs
		{
			get
			{
				return this._Tbl_LichSuLamViecs;
			}
			set
			{
				this._Tbl_LichSuLamViecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_CTKyLuatNVs(Tbl_CTKyLuatNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NhanVien = this;
		}
		
		private void detach_Tbl_CTKyLuatNVs(Tbl_CTKyLuatNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NhanVien = null;
		}
		
		private void attach_Tbl_CTThamGiaDTNVs(Tbl_CTThamGiaDTNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NhanVien = this;
		}
		
		private void detach_Tbl_CTThamGiaDTNVs(Tbl_CTThamGiaDTNV entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NhanVien = null;
		}
		
		private void attach_Tbl_LichSuLamViecs(Tbl_LichSuLamViec entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NhanVien = this;
		}
		
		private void detach_Tbl_LichSuLamViecs(Tbl_LichSuLamViec entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_PhongBan")]
	public partial class Tbl_PhongBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPB;
		
		private string _tenPB;
		
		private string _diaDiem;
		
		private string _soDT;
		
		private EntitySet<Tbl_LichSuLamViec> _Tbl_LichSuLamViecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPBChanging(string value);
    partial void OnmaPBChanged();
    partial void OntenPBChanging(string value);
    partial void OntenPBChanged();
    partial void OndiaDiemChanging(string value);
    partial void OndiaDiemChanged();
    partial void OnsoDTChanging(string value);
    partial void OnsoDTChanged();
    #endregion
		
		public Tbl_PhongBan()
		{
			this._Tbl_LichSuLamViecs = new EntitySet<Tbl_LichSuLamViec>(new Action<Tbl_LichSuLamViec>(this.attach_Tbl_LichSuLamViecs), new Action<Tbl_LichSuLamViec>(this.detach_Tbl_LichSuLamViecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPB", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPB
		{
			get
			{
				return this._maPB;
			}
			set
			{
				if ((this._maPB != value))
				{
					this.OnmaPBChanging(value);
					this.SendPropertyChanging();
					this._maPB = value;
					this.SendPropertyChanged("maPB");
					this.OnmaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenPB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenPB
		{
			get
			{
				return this._tenPB;
			}
			set
			{
				if ((this._tenPB != value))
				{
					this.OntenPBChanging(value);
					this.SendPropertyChanging();
					this._tenPB = value;
					this.SendPropertyChanged("tenPB");
					this.OntenPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaDiem", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diaDiem
		{
			get
			{
				return this._diaDiem;
			}
			set
			{
				if ((this._diaDiem != value))
				{
					this.OndiaDiemChanging(value);
					this.SendPropertyChanging();
					this._diaDiem = value;
					this.SendPropertyChanged("diaDiem");
					this.OndiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDT", DbType="VarChar(15)")]
		public string soDT
		{
			get
			{
				return this._soDT;
			}
			set
			{
				if ((this._soDT != value))
				{
					this.OnsoDTChanging(value);
					this.SendPropertyChanging();
					this._soDT = value;
					this.SendPropertyChanged("soDT");
					this.OnsoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_PhongBan_Tbl_LichSuLamViec", Storage="_Tbl_LichSuLamViecs", ThisKey="maPB", OtherKey="maPB")]
		public EntitySet<Tbl_LichSuLamViec> Tbl_LichSuLamViecs
		{
			get
			{
				return this._Tbl_LichSuLamViecs;
			}
			set
			{
				this._Tbl_LichSuLamViecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_LichSuLamViecs(Tbl_LichSuLamViec entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_PhongBan = this;
		}
		
		private void detach_Tbl_LichSuLamViecs(Tbl_LichSuLamViec entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_PhongBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_LichSuLamViec")]
	public partial class Tbl_LichSuLamViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNV;
		
		private string _maPB;
		
		private string _maChucVu;
		
		private System.DateTime _ngayBD;
		
		private System.Nullable<System.DateTime> _ngayKT;
		
		private EntityRef<Tbl_ChucVu> _Tbl_ChucVu;
		
		private EntityRef<Tbl_NhanVien> _Tbl_NhanVien;
		
		private EntityRef<Tbl_PhongBan> _Tbl_PhongBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNVChanging(string value);
    partial void OnmaNVChanged();
    partial void OnmaPBChanging(string value);
    partial void OnmaPBChanged();
    partial void OnmaChucVuChanging(string value);
    partial void OnmaChucVuChanged();
    partial void OnngayBDChanging(System.DateTime value);
    partial void OnngayBDChanged();
    partial void OnngayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKTChanged();
    #endregion
		
		public Tbl_LichSuLamViec()
		{
			this._Tbl_ChucVu = default(EntityRef<Tbl_ChucVu>);
			this._Tbl_NhanVien = default(EntityRef<Tbl_NhanVien>);
			this._Tbl_PhongBan = default(EntityRef<Tbl_PhongBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNV
		{
			get
			{
				return this._maNV;
			}
			set
			{
				if ((this._maNV != value))
				{
					if (this._Tbl_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNVChanging(value);
					this.SendPropertyChanging();
					this._maNV = value;
					this.SendPropertyChanged("maNV");
					this.OnmaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPB", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPB
		{
			get
			{
				return this._maPB;
			}
			set
			{
				if ((this._maPB != value))
				{
					if (this._Tbl_PhongBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPBChanging(value);
					this.SendPropertyChanging();
					this._maPB = value;
					this.SendPropertyChanged("maPB");
					this.OnmaPBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					if (this._Tbl_ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBD", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngayBD
		{
			get
			{
				return this._ngayBD;
			}
			set
			{
				if ((this._ngayBD != value))
				{
					this.OnngayBDChanging(value);
					this.SendPropertyChanging();
					this._ngayBD = value;
					this.SendPropertyChanged("ngayBD");
					this.OnngayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKT", DbType="Date")]
		public System.Nullable<System.DateTime> ngayKT
		{
			get
			{
				return this._ngayKT;
			}
			set
			{
				if ((this._ngayKT != value))
				{
					this.OnngayKTChanging(value);
					this.SendPropertyChanging();
					this._ngayKT = value;
					this.SendPropertyChanged("ngayKT");
					this.OnngayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_ChucVu_Tbl_LichSuLamViec", Storage="_Tbl_ChucVu", ThisKey="maChucVu", OtherKey="maChucVu", IsForeignKey=true)]
		public Tbl_ChucVu Tbl_ChucVu
		{
			get
			{
				return this._Tbl_ChucVu.Entity;
			}
			set
			{
				Tbl_ChucVu previousValue = this._Tbl_ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_ChucVu.Entity = null;
						previousValue.Tbl_LichSuLamViecs.Remove(this);
					}
					this._Tbl_ChucVu.Entity = value;
					if ((value != null))
					{
						value.Tbl_LichSuLamViecs.Add(this);
						this._maChucVu = value.maChucVu;
					}
					else
					{
						this._maChucVu = default(string);
					}
					this.SendPropertyChanged("Tbl_ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_NhanVien_Tbl_LichSuLamViec", Storage="_Tbl_NhanVien", ThisKey="maNV", OtherKey="maNV", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tbl_NhanVien Tbl_NhanVien
		{
			get
			{
				return this._Tbl_NhanVien.Entity;
			}
			set
			{
				Tbl_NhanVien previousValue = this._Tbl_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_NhanVien.Entity = null;
						previousValue.Tbl_LichSuLamViecs.Remove(this);
					}
					this._Tbl_NhanVien.Entity = value;
					if ((value != null))
					{
						value.Tbl_LichSuLamViecs.Add(this);
						this._maNV = value.maNV;
					}
					else
					{
						this._maNV = default(string);
					}
					this.SendPropertyChanged("Tbl_NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_PhongBan_Tbl_LichSuLamViec", Storage="_Tbl_PhongBan", ThisKey="maPB", OtherKey="maPB", IsForeignKey=true)]
		public Tbl_PhongBan Tbl_PhongBan
		{
			get
			{
				return this._Tbl_PhongBan.Entity;
			}
			set
			{
				Tbl_PhongBan previousValue = this._Tbl_PhongBan.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_PhongBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_PhongBan.Entity = null;
						previousValue.Tbl_LichSuLamViecs.Remove(this);
					}
					this._Tbl_PhongBan.Entity = value;
					if ((value != null))
					{
						value.Tbl_LichSuLamViecs.Add(this);
						this._maPB = value.maPB;
					}
					else
					{
						this._maPB = default(string);
					}
					this.SendPropertyChanged("Tbl_PhongBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_User")]
	public partial class Tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Password;
		
		private string _Nhom;
		
		private string _Phanquyen;
		
		private string _MaNV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNhomChanging(string value);
    partial void OnNhomChanged();
    partial void OnPhanquyenChanging(string value);
    partial void OnPhanquyenChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public Tbl_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nhom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nhom
		{
			get
			{
				return this._Nhom;
			}
			set
			{
				if ((this._Nhom != value))
				{
					this.OnNhomChanging(value);
					this.SendPropertyChanging();
					this._Nhom = value;
					this.SendPropertyChanged("Nhom");
					this.OnNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phanquyen", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Phanquyen
		{
			get
			{
				return this._Phanquyen;
			}
			set
			{
				if ((this._Phanquyen != value))
				{
					this.OnPhanquyenChanging(value);
					this.SendPropertyChanging();
					this._Phanquyen = value;
					this.SendPropertyChanged("Phanquyen");
					this.OnPhanquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(250)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
